'''
Texture node: a single node provides a Hash output and a Slot output
- Hash output (SSMTSocketObject): treated as an "object" in the blueprint chain; generates a standalone [TextureOverride_<hash>] + [Resource<name>]
- Slot output (SSMTSocketTexture): connects to the Object Info texture slot input; generates ps-tX = Resource<name>
'''
import os

import bpy

from ..common.texture_naming import (
    default_texture_filename,
    default_texture_resource_name,
    normalize_texture_filename,
    normalize_texture_resource_name,
)
from .blueprint_node_base import SSMTNodeBase


def _get_default_texture_filename(texture_hash: str, mark_name: str) -> str:
    return default_texture_filename(texture_hash, mark_name)


# Preview image mtime cache: {preview path: mtime}
# Reload the image when the source file changes so the preview stays in sync after the texture is replaced.
_preview_mtime_cache: dict = {}


class SSMTNode_Texture(SSMTNodeBase):
    '''Texture node'''
    bl_idname = 'SSMTNode_Texture'
    bl_label = 'Texture'
    bl_icon = 'IMAGE_DATA'

    texture_hash: bpy.props.StringProperty(
        name="Hash",
        description="8-digit hexadecimal texture Hash",
        default="",
        update=lambda self, ctx: self._refresh_label(),
    )  # type: ignore

    mark_name: bpy.props.StringProperty(
        name="Mark Name",
        description="Used for comments and the default file name",
        default="",
        update=lambda self, ctx: self._refresh_label(),
    )  # type: ignore

    resource_name: bpy.props.StringProperty(
        name="Resource Name",
        description="Uses Resource_<MapType>_<Hash> when left empty",
        default="",
    )  # type: ignore

    texture_filename: bpy.props.StringProperty(
        name="File Name",
        description="File name in the output directory; uses <Hash>_<MapType>.dds when left empty",
        default="",
    )  # type: ignore

    texture_filepath: bpy.props.StringProperty(
        name="File Path",
        description="Path to the source texture file",
        subtype='FILE_PATH',
        default="",
    )  # type: ignore

    texture_format: bpy.props.EnumProperty(
        name="Target Format",
        description="DXGI format this texture is converted to when generating the Mod; no conversion when empty/unknown",
        items=[
            ('AUTO', "Auto / No Conversion", "Does not convert the source file format"),
            ('BC7_UNORM', 'BC7_UNORM', 'BC7_UNORM'),
            ('BC7_UNORM_SRGB', 'BC7_UNORM_SRGB', 'BC7_UNORM_SRGB'),
            ('R8G8B8A8_UNORM', 'R8G8B8A8_UNORM', 'R8G8B8A8_UNORM'),
            ('R8G8B8A8_UNORM_SRGB', 'R8G8B8A8_UNORM_SRGB', 'R8G8B8A8_UNORM_SRGB'),
            ('R10G10B10A2_UNORM', 'R10G10B10A2_UNORM', 'R10G10B10A2_UNORM'),
            ('R11G11B10_FLOAT', 'R11G11B10_FLOAT', 'R11G11B10_FLOAT'),
            ('BC5_UNORM', 'BC5_UNORM', 'BC5_UNORM'),
            ('CUSTOM', 'Custom', 'Enter the target format manually'),
        ],
        default='AUTO',
    )  # type: ignore

    texture_format_custom: bpy.props.StringProperty(
        name="Custom Format",
        description="DXGI format name entered manually",
        default="",
    )  # type: ignore

    @property
    def effective_texture_format(self) -> str:
        """Return the effective target format string; an empty string means no conversion."""
        fmt = self.texture_format
        if fmt == 'CUSTOM':
            return self.texture_format_custom.strip()
        if fmt == 'AUTO':
            return ''
        return fmt

    def _resolve_preview_path(self) -> str:
        """Resolve the image path used for the preview: prefer the same-named .jpg (the preview image generated by SSMT),
        otherwise try loading the source file directly (Blender can read DDS)."""
        path = str(self.texture_filepath or "").strip()
        if not path:
            return ""
        path = bpy.path.abspath(path)
        if not os.path.isfile(path):
            return ""
        jpg_path = os.path.splitext(path)[0] + ".jpg"
        if os.path.isfile(jpg_path):
            return jpg_path
        return path

    def _get_preview_image(self):
        preview_path = self._resolve_preview_path()
        if not preview_path:
            return None
        try:
            mtime = os.path.getmtime(preview_path)
        except OSError:
            return None
        try:
            image = bpy.data.images.load(preview_path, check_existing=True)
        except Exception as e:
            print(f"[TexturePreview] Failed to load preview: {preview_path}, {e}")
            return None
        # Reload when the source file changes so the preview stays in sync after the texture is replaced.
        # Note: the cache must live in a module-level dict, not in node properties —
        # Blender forbids writing to ID data blocks from within a draw callback (AttributeError).
        if abs(_preview_mtime_cache.get(preview_path, -1.0) - mtime) > 1e-6:
            try:
                image.reload()
            except Exception:
                pass
            _preview_mtime_cache[preview_path] = mtime
        try:
            image.preview_ensure()
        except Exception:
            return None
        return image

    def _refresh_label(self):
        if self.texture_hash:
            self.label = f"Texture {self.texture_hash}"
        else:
            self.label = "Texture"

    def get_resource_name(self) -> str:
        name = self.resource_name.strip()
        return normalize_texture_resource_name(name) if name else default_texture_resource_name(self.texture_hash, self.mark_name)

    def get_texture_filename(self) -> str:
        filename = self.texture_filename.strip()
        return normalize_texture_filename(filename) if filename else _get_default_texture_filename(
            self.texture_hash, self.mark_name
        )

    def init(self, context):
        self.width = 220
        self._refresh_label()
        # Hash output: used as an "object"; can connect to Group/SwitchKey/Output
        self.outputs.new('SSMTSocketObject', "Hash")
        # Slot output: connects to the Object Info texture slot input
        self.outputs.new('SSMTSocketTexture', "Slot")

    def draw_buttons(self, context, layout):
        col = layout.column(align=True)
        col.prop(self, "texture_hash", text="Hash")
        col.prop(self, "mark_name", text="Mark Name")
        col.prop(self, "resource_name", text="Resource Name")
        col.prop(self, "texture_filename", text="File Name")
        col.prop(self, "texture_filepath", text="File Path")
        col.prop(self, "texture_format", text="Target Format")
        if self.texture_format == 'CUSTOM':
            col.prop(self, "texture_format_custom", text="Custom Format")

        if not self.texture_hash:
            layout.label(text="Cannot generate config when Hash is empty", icon='ERROR')

        # Preview drawing must be fault-tolerant: no exception in the draw context may break the node itself
        try:
            preview_image = self._get_preview_image()
            if preview_image is not None and getattr(preview_image, "preview", None):
                layout.template_icon(icon_value=preview_image.preview.icon_id, scale=6.0)
        except Exception as e:
            print(f"[TexturePreview] Failed to draw preview: {e}")


classes = (
    SSMTNode_Texture,
)


def register():
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
