import hashlib


class M_SectionType:
    NameSpace = "NameSpace"
    Present = "Present"
    Constants = "Constants"
    Key = "Key"

    TextureOverrideIB = "TextureOverrideIB"
    TextureOverrideVB = "TextureOverrideVB"
    TextureOverrideVertexLimitRaise = "TextureOverrideVertexLimitRaise"
    TextureOverrideTexture = "TextureOverrideTexture"
    TextureOverrideGeneral = "TextureOverrideGeneral" # generic type other than VB/IB/VLR
    TextureOverrideShapeKeys = "TextureOverrideShapeKeys" # for Unreal shape keys, currently only tested with WWMI

    IBSkip = "IBSkip"

    ResourceBuffer = "ResourceBuffer"
    ResourceTexture = "ResourceTexture"
    ResourceAndTextureOverride_Texture = "ResourceAndTextureOverride_Texture" # used in Hash-style textures to keep Resource and TextureOverride together
    ResourceModInfo = "ResourceModInfo" # the Mod author info section inside WWMI
    ResourceShapeKeysOverride = "ResourceShapeKeysOverride"
    ResourceSkeletonOverride = "ResourceSkeletonOverride"

    VertexShaderCheck = "VertexShaderCheck"

    CreditInfo = "CreditInfo"
    CommandList = "CommandList"
    CustomShader = "CustomShader"

    # Section types related to cross-IB
    CrossIBPresent = "CrossIBPresent"
    ResourceID = "ResourceID"
    CrossIBShaderOverride = "CrossIBShaderOverride"
    CrossIBTextureOverride = "CrossIBTextureOverride"


class M_IniSection:
    def __init__(self,section_type:M_SectionType) -> None:
        self.SectionType:M_SectionType = section_type
        self.SectionName = "" # Constants and Present can set this to avoid adding a [name] line
        self.SectionLineList = []
    
    def empty(self)->bool:
        '''
        Check whether this section is empty or holds only new lines. If any line is
        neither empty nor a new line, the section is not empty and False is returned;
        otherwise, if no actual content is found after scanning everything, True is
        returned to indicate that the section is empty.
        '''
        for line in self.SectionLineList:
            if line != "" and line != "\n":
                return False
        return True

    def append(self,line:str):
        self.SectionLineList.append(line)

    def new_line(self):
        '''
        append a new line.
        '''
        self.SectionLineList.append("")


class M_IniBuilder:
    def __init__(self):
        self.line_list = []
        self.ini_section_list:list[M_IniSection] = []

        # Tracks whether a section with this name has appeared for the first time
        self.ini_section_name_set:set = set()
        self._custom_shader_sections_appended = False
    
    def clear(self):
        self.line_list.clear()
        self.ini_section_list.clear()
        self.ini_section_name_set.clear()
        self._custom_shader_sections_appended = False

    def __append_section_line(self,ini_section_type:M_SectionType):
        '''
        Only can be legally call in M_IniBuilder.
        '''
        for ini_section in self.ini_section_list:
            if ini_section.SectionType == ini_section_type:
                section_name_exists = ini_section.SectionName in self.ini_section_name_set
                if not section_name_exists:
                    self.line_list.append("\n;MARK:" + ini_section_type + "\n")

                # Only auto-fill SectionName when it is not empty; otherwise it is user controlled
                if ini_section.SectionName != "" and not section_name_exists:
                    self.line_list.append("[" + ini_section.SectionName + "]\n")
                    self.ini_section_name_set.add(ini_section.SectionName)

                # Append the section content
                for line in ini_section.SectionLineList:
                    self.line_list.append(line + "\n")
                

    def append_section(self,m_inisection:M_IniSection):
        # First check whether it is empty; if so, do not add it
        if not m_inisection.empty():
            self.ini_section_list.append(m_inisection)
    
    def save_to_file_not_reorder(self,config_ini_path:str):
        '''
        Non-reordering version, so our ini format can be easily compared with ini files generated by other tools.
        '''
        from .m_custom_shader_helper import M_CustomShaderHelper
        M_CustomShaderHelper.append_sections(self)

        current_section_name = None
        for ini_section in self.ini_section_list:
            section_name_exists = ini_section.SectionName == current_section_name
            if ini_section.SectionName == "":
                current_section_name = None
            # if not section_name_exists:
            #     self.line_list.append("\n;MARK:" + ini_section.SectionType + "\n")
            
            # Only auto-fill SectionName when it is not empty; otherwise it is user controlled
            if ini_section.SectionName != "" and not section_name_exists:
                self.line_list.append("[" + ini_section.SectionName + "]\n")
                current_section_name = ini_section.SectionName

            # Append the section content
            for line in ini_section.SectionLineList:
                self.line_list.append(line + "\n")

        # Add tools credit.
        
        # self.line_list.append("\n\n; Mod generated by MIMIBlender.\n")
        
        # Add sha256 to verify if ini need to overwrite.
        sha256 = self.calculate_sha256_for_list(self.line_list)
        # print("sha256: " + sha256)

        # Add after sha256 calculation.
        self.line_list.append("\n;sha256=" + sha256 + "\n\n") 


        # Read ini and find sha256, if not same then write ini, if same do nothing.
        ini_sha256 = self.get_sha256_from_ini(config_ini_path)
        # print("old ini sha256: " + ini_sha256)
        # print("new ini sha256: " + sha256)
        if ini_sha256 != sha256:
            print("Write new mod ini because sha256 is not same.")
            with open(config_ini_path,"w") as f:
                f.writelines(self.line_list)
        else:
            print("Skip write mod ini becuase sha256 is same, ini file content not changed so we are safe to skip.")
        pass

    def save_to_file(self,config_ini_path:str):
        from .m_custom_shader_helper import M_CustomShaderHelper
        M_CustomShaderHelper.append_sections(self)

        self.__append_section_line(M_SectionType.CrossIBPresent)
        
        self.__append_section_line(M_SectionType.ResourceID)

        self.__append_section_line(M_SectionType.NameSpace)

        self.__append_section_line(M_SectionType.Key)

        self.__append_section_line(M_SectionType.Constants)

        self.__append_section_line(M_SectionType.Present)


        self.__append_section_line(M_SectionType.IBSkip)


        self.__append_section_line(M_SectionType.TextureOverrideVertexLimitRaise)

        self.__append_section_line(M_SectionType.TextureOverrideVB)

        self.__append_section_line(M_SectionType.TextureOverrideIB)

        self.__append_section_line(M_SectionType.TextureOverrideShapeKeys)

        self.__append_section_line(M_SectionType.TextureOverrideGeneral)

        self.__append_section_line(M_SectionType.CommandList)

        self.__append_section_line(M_SectionType.ResourceShapeKeysOverride)

        self.__append_section_line(M_SectionType.ResourceSkeletonOverride)

        self.__append_section_line(M_SectionType.ResourceBuffer)

        self.__append_section_line(M_SectionType.ResourceTexture)

        self.__append_section_line(M_SectionType.TextureOverrideTexture)

        self.__append_section_line(M_SectionType.ResourceAndTextureOverride_Texture)

        self.__append_section_line(M_SectionType.ResourceModInfo)


        self.__append_section_line(M_SectionType.VertexShaderCheck)
        
        self.__append_section_line(M_SectionType.CreditInfo)

        self.__append_section_line(M_SectionType.CustomShader)


        # Add tools credit.
        
        # self.line_list.append("\n\n; Mod generated by MIMIBlender.\n")

        # Add sha256 to verify if ini need to overwrite.
        sha256 = self.calculate_sha256_for_list(self.line_list)
        # print("sha256: " + sha256)

        # Add after sha256 calculation.
        self.line_list.append("\n;sha256=" + sha256 + "\n\n") 


        # Read ini and find sha256, if not same then write ini, if same do nothing.
        ini_sha256 = self.get_sha256_from_ini(config_ini_path)
        # print("old ini sha256: " + ini_sha256)
        # print("new ini sha256: " + sha256)
        if ini_sha256 != sha256:
            print("Write new mod ini because sha256 is not same.")
            with open(config_ini_path,"w") as f:
                f.writelines(self.line_list)
        else:
            print("Skip write mod ini becuase sha256 is same, ini file content not changed so we are safe to skip.")

    def calculate_sha256_for_list(self,string_list):
        # Create a new sha256 hash object
        sha256_hash = hashlib.sha256()
        
        # Encode each string in the list as bytes and update the hash object
        for line in string_list:
            byte_line = line.encode('utf-8')
            sha256_hash.update(byte_line)
        
        # Get the hash value in hexadecimal format
        hex_digest = sha256_hash.hexdigest()
        
        return hex_digest

    def get_sha256_from_ini(self,ini_file_path:str):
        """
        Read the INI file at the given path, find the line starting with ;sha256=,
        and return the content after ;sha256= on that line (leading/trailing whitespace stripped).
        Returns an empty string if it is not found or an error occurs.
        """
        sha256_value = ""
        
        try:
            with open(ini_file_path, 'r', encoding='utf-8') as file:
                for line in file:
                    # Strip leading and trailing whitespace
                    stripped_line = line.strip()
                    
                    # Check whether the line starts with ";sha256="
                    if stripped_line.startswith(";sha256="):
                        # Extract the content after ";sha256=" and strip whitespace
                        sha256_value = stripped_line[len(";sha256="):].strip()
                        break  # stop after finding it, assuming only one line matches
                        
        except FileNotFoundError:
            print(f"The file at {ini_file_path} was not found.")
            return ""
        except Exception as e:
            print(f"An error occurred: {e}")
            return ""
            
        return sha256_value

