"""Tests for the optional simulated XXMI Tools tail comments.

Run with blender -b --factory-startup --python-exit-code 1 --python this_file.

The option is meant to make a generated INI end exactly like one produced by
XXMI Tools (leotorrez/XXMITools), except that the tool version is left out and
our own sha256 line has to stay the last line of the file.
"""
import importlib
import os
from pathlib import Path
import sys
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import patch

import bpy

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parent))
addon = importlib.import_module(ROOT.name)
addon.register()

from MIMIBlender.common.m_ini_builder import (
    M_IniBuilder,
    M_IniSection,
    M_SectionType,
    XXMI_TAIL_COMMENT_LINES,
)
from MIMIBlender.common.mimi_global_properties import MIMIGlobalProperties

GENERATED_LINE = "; .ini generated by XXMI (XX-Model-Importer)"
ISSUES_LINE = (
    "; If you have any issues or find any bugs, please open a ticket at "
    "https://github.com/leotorrez/XXMI-Tools/issues"
)


class LayoutRecorder:
    """Record node controls without needing a live node editor area."""

    def __init__(self):
        self.properties = []
        self.prop_texts = []
        self.operators = []
        self.labels = []

    def row(self, **kwargs):
        return self

    def column(self, **kwargs):
        return self

    def box(self, **kwargs):
        return self

    def label(self, **kwargs):
        self.labels.append(kwargs.get('text', ''))

    def prop(self, data, name, **kwargs):
        self.properties.append(name)
        self.prop_texts.append(kwargs.get('text', ''))

    def operator(self, name, **kwargs):
        self.operators.append(name)
        return SimpleNamespace()


def read_text(path):
    """Read a generated INI as text; the writer uses the platform encoding."""
    with open(path, 'r', encoding='utf-8', errors='replace') as file:
        return file.read()


class XxmiTailCommentTests(unittest.TestCase):
    def setUp(self):
        self.tmp_root = ROOT / 'tmp'
        self.tmp_root.mkdir(exist_ok=True)
        self._temp = tempfile.TemporaryDirectory(dir=str(self.tmp_root))
        self.addCleanup(self._temp.cleanup)
        self.ini_path = os.path.join(self._temp.name, 'test_mod.ini')
        self.properties = bpy.context.scene.mimi_global_properties
        self.previous_flag = self.properties.simulate_xxmi_tail_comments
        self.properties.simulate_xxmi_tail_comments = False
        self.addCleanup(setattr, self.properties, 'simulate_xxmi_tail_comments', self.previous_flag)

    def build_ini(self):
        """Render one small INI through the real save path."""
        builder = M_IniBuilder()
        section = M_IniSection(M_SectionType.TextureOverrideIB)
        section.append('[TextureOverrideComponent0]')
        section.append('hash = 82aa82e1')
        section.new_line()
        builder.append_section(section)
        builder.save_to_file(self.ini_path)

    def test_disabled_keeps_the_file_unchanged(self):
        self.build_ini()
        text = read_text(self.ini_path)
        self.assertNotIn('XXMI', text)
        self.assertNotIn('XX-Model-Importer', text)
        self.assertTrue(text.rstrip('\n').splitlines()[-1].startswith(';sha256='))

    def test_enabled_appends_the_exact_xxmi_lines(self):
        self.properties.simulate_xxmi_tail_comments = True
        self.build_ini()
        text = read_text(self.ini_path)
        lines = text.splitlines()

        self.assertIn(GENERATED_LINE, lines)
        self.assertIn(ISSUES_LINE, lines)
        # Verbatim copy: same text and same order as the XXMI Tools template.
        self.assertEqual(list(XXMI_TAIL_COMMENT_LINES), [GENERATED_LINE, ISSUES_LINE])
        self.assertEqual(lines[lines.index(GENERATED_LINE) + 1], ISSUES_LINE)
        # The tool version is deliberately not reproduced.
        self.assertNotIn('XX-Model-Importer) v', text)

        # Exactly one blank line separates the content from the comments, the
        # same spacing a real XXMI Tools file uses.
        generated_index = lines.index(GENERATED_LINE)
        self.assertEqual(lines[generated_index - 1], '')
        self.assertNotEqual(lines[generated_index - 2], '')

        # sha256 stays the last line of the file, right after the comments.
        last_line = text.rstrip('\n').splitlines()[-1]
        self.assertTrue(last_line.startswith(';sha256='), last_line)
        self.assertLess(lines.index(ISSUES_LINE), [index for index, line in enumerate(lines) if line.startswith(';sha256=')][0])

    def test_toggling_rewrites_the_file(self):
        self.build_ini()
        first_stat = os.stat(self.ini_path)

        # Same option again: the change detection must skip the write.
        self.build_ini()
        self.assertEqual(os.stat(self.ini_path).st_mtime_ns, first_stat.st_mtime_ns)

        # Turning it on must rewrite, even though the sections did not change.
        self.properties.simulate_xxmi_tail_comments = True
        self.build_ini()
        enabled_text = read_text(self.ini_path)
        self.assertIn(GENERATED_LINE, enabled_text)
        self.assertNotEqual(read_text(self.ini_path), None)

        # Turning it off must remove the comments again.
        self.properties.simulate_xxmi_tail_comments = False
        self.build_ini()
        disabled_text = read_text(self.ini_path)
        self.assertNotIn('XX-Model-Importer', disabled_text)
        self.assertTrue(disabled_text.rstrip('\n').splitlines()[-1].startswith(';sha256='))

    def test_ntemi_writer_uses_the_same_tail(self):
        from MIMIBlender.games.ntemi import sections

        ntemi_path = os.path.join(self._temp.name, 'ntemi_mod.ini')
        self.properties.simulate_xxmi_tail_comments = True
        sections.write_ini(ntemi_path, ['[Constants]', 'global $x = 1'])
        text = read_text(ntemi_path)
        self.assertIn(GENERATED_LINE, text)
        self.assertIn(ISSUES_LINE, text)
        self.assertTrue(text.rstrip('\n').splitlines()[-1].startswith(';sha256='))

    def test_generate_mod_node_draws_the_checkbox(self):
        tree = bpy.data.node_groups.new('xxmi_tail', 'MIMIBlueprintTreeType')
        self.addCleanup(bpy.data.node_groups.remove, tree)
        node = tree.nodes.new('MIMINode_Result_Output')

        recorder = LayoutRecorder()
        # The shape key block needs a bigger fake layout than this recorder is.
        with patch('MIMIBlender.blueprint.blueprint_node_shapekey.draw_shapekey_settings'):
            node.draw_buttons(bpy.context, recorder)
        self.assertIn('simulate_xxmi_tail_comments', recorder.properties)
        self.assertIn('Simulate XXMI Tail Comments', recorder.prop_texts)
        self.assertFalse(self.properties.simulate_xxmi_tail_comments)

        # The label follows the add-on language switch.
        from MIMIBlender.i18n import i18n
        previous_language = i18n.get_language()
        self.addCleanup(i18n.apply_language, previous_language)
        i18n.apply_language('zh')
        recorder = LayoutRecorder()
        with patch('MIMIBlender.blueprint.blueprint_node_shapekey.draw_shapekey_settings'):
            node.draw_buttons(bpy.context, recorder)
        self.assertIn('模拟 XXMI 结尾注释', recorder.prop_texts)

    def test_accessor_reads_the_scene_option(self):
        self.assertIs(MIMIGlobalProperties.simulate_xxmi_tail_comments(), False)
        self.properties.simulate_xxmi_tail_comments = True
        self.assertIs(MIMIGlobalProperties.simulate_xxmi_tail_comments(), True)


if __name__ == '__main__':
    try:
        suite = unittest.defaultTestLoader.loadTestsFromTestCase(XxmiTailCommentTests)
        result = unittest.TextTestRunner(verbosity=2).run(suite)
    finally:
        addon.unregister()
    if not result.wasSuccessful():
        raise AssertionError('XXMI tail comment tests failed')
